### ISSUE TITLE
Move `master` branch to `main`

### ISSUE THREAD

**Issue by jennybc** [tidyverse/blob#23]
The `master` branch of this repository will soon be renamed to `main`, as part of a coordinated change across several GitHub organizations (including, but not limited to: [tidyverse](https://github.com/tidyverse), [r-lib](https://github.com/r-lib), [tidymodels](https://github.com/tidymodels), and [sol-eng](https://github.com/sol-eng)). We anticipate this will happen by the end of September 2021.

That will be preceded by a release of the [usethis package](https://usethis.r-lib.org), which will gain some functionality around detecting and adapting to a renamed default branch. There will also be a blog post at the time of this `master` --> `main` change.

The purpose of this issue is to:

* Help us firm up the list of targetted repositories
* Make sure all maintainers are aware of what's coming
* Give us an issue to close when the job is done
* Give us a place to put advice for collaborators re: how to adapt

*message id: euphoric_snowdog*

**Comment by krlmlr** [comment]
Thanks. I attempted to run `git_default_branch_rediscover()` without `GITHUB_PAT` and got, with dev usethis:

```
d> usethis::git_default_branch_rediscover()
Error in `abort()`: `message` must be a character vector.
Backtrace:
    ▆
 1. └─usethis::git_default_branch_rediscover()
 2.   └─usethis:::rediscover_default_branch(old_name = current_local_default)
 3.     └─usethis:::check_for_config(...)
 4.       └─usethis:::check_for_maybe_config(cfg)
 5.         └─usethis:::stop_maybe_github_remote_config(cfg)
 6.           └─rlang::abort(...)
 7.             └─rlang:::validate_signal_args(message, class, call, .subclass) at rlang/R/cnd-abort.R:233:2
```

All fine now, thanks for working on this!

**Comment by jennybc** [comment]
I can't replicate that. I deleted my PAT from the macOS Keychain and I see this:

```
> library(usethis)
> git_default_branch_rediscover()
✓ Setting active project to '/Users/jenny/tmp/carole'
Error: Unable to get GitHub info for these remotes: 'origin'
Are we offline? Is GitHub down? Has the repo been deleted?
Otherwise, you probably need to configure a personal access token (PAT) for 'github.com'
See `?gh_token_help` for advice
Run `rlang::last_error()` to see where the error occurred.
> packageVersion("usethis")
[1] '2.1.1'
> packageVersion("rlang")
[1] '0.4.11'
```

Note that usethis 2.1.1 is in the CRAN submission queue, but it's not different from 2.1.0 in any way that relates to this.

Are you maybe on a different version of ... rlang?

**Comment by krlmlr** [comment]
Done now.
