### ISSUE TITLE
Missing blob?

### ISSUE THREAD

**Issue by MichaelChirico** [tidyverse/blob#26]
What's the proper way to represent missingness in `blob`?

is it a `NULL` element of the list vector?

```
as_blob(NA)
```

returns `list(NULL)`

and

```
as_blob(list(NULL, as.raw(0)))
```

returns `list(NULL, as.raw(0))`

but

```
as_blob(NA_character_)
```

returns `list(charToRaw("NA"))`

Missingness is not mentioned in the help anywhere, nor in the README. Is missingness intended to be supported? Is the `as_blob(NA_character_)` result a bug?

**Comment by MichaelChirico** [comment]
(it looks like `charToRaw(NA_character_)` also returns `charToRaw("NA")` which seems like a base R bug 😅)

**Comment by krlmlr** [comment]
``` r
dput(blob::blob()[NA_integer_])
#> structure(list(NULL), ptype = raw(0), class = c("blob", "vctrs_list_of", 
#> "vctrs_vctr", "list"))
```

<sup>Created on 2022-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The `NA_character_` thing is a bug, would you like to submit a PR?

**Comment by MichaelChirico** [comment]
Looks like it's a `vctrs` bug?

```
vctrs::vec_cast(NA_character_, new_blob())
# <blob[1]>
# [1] blob[2 B]
```

Should the fix go there or here?
